apiVersion: v1
kind: Service
metadata:
  name: "notification-receiver"
  labels:
    app: notification-receiver
    {{- include "notification-receiver.selectorLabels" . | nindent 8 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include notification-receiver.selectorLabels" . | nindent 4 }}