apiVersion: v1
kind: Service
metadata:
  name: "notification-receiver"
  labels:
    {{- include "notification-receiver.labels" . | nindent 4 }}
{{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "notification-receiver.selectorLabels" . | nindent 6 }}